local Hand = require("objects/hand")

local function createHands()
    return {
        Hand:new({
            name = "High Roll",
            base_score = 5,
            multiplier = 1,
            priority = 1,
            min_dice = 1,
            description = "Highest single die",
        }),
        Hand:new({
            name = "Pair",
            base_score = 10,
            multiplier = 1.5,
            priority = 2,
            min_dice = 2,
            description = "Two dice of the same value",
        }),
        Hand:new({
            name = "Two Pair",
            base_score = 20,
            multiplier = 1.5,
            priority = 3,
            min_dice = 4,
            description = "Two different pairs",
        }),
        Hand:new({
            name = "X of a Kind",
            base_score = 30,
            multiplier = 2,
            priority = 4,
            min_dice = 3,
            is_x_of_a_kind = true,
            description = "3+ matching dice -- scales with count",
        }),
        Hand:new({
            name = "Small Straight",
            base_score = 30,
            multiplier = 2.5,
            priority = 5,
            min_dice = 4,
            description = "Four consecutive values",
        }),
        Hand:new({
            name = "Full House",
            base_score = 40,
            multiplier = 2.5,
            priority = 6,
            min_dice = 5,
            description = "Three of a kind + a pair",
        }),
        Hand:new({
            name = "Large Straight",
            base_score = 45,
            multiplier = 3,
            priority = 7,
            min_dice = 5,
            description = "Five consecutive values",
        }),
        Hand:new({
            name = "All Even",
            base_score = 40,
            multiplier = 2,
            priority = 8,
            min_dice = 5,
            description = "Every die shows an even value (2/4/6)",
        }),
        Hand:new({
            name = "All Odd",
            base_score = 40,
            multiplier = 2,
            priority = 9,
            min_dice = 5,
            description = "Every die shows an odd value (1/3/5)",
        }),
        Hand:new({
            name = "Three Pairs",
            base_score = 50,
            multiplier = 3,
            priority = 10,
            min_dice = 6,
            description = "Three different pairs (6+ dice)",
        }),
        Hand:new({
            name = "Two Triplets",
            base_score = 65,
            multiplier = 4,
            priority = 11,
            min_dice = 6,
            description = "Two sets of three of a kind (6+ dice)",
        }),
        Hand:new({
            name = "Full Run",
            base_score = 80,
            multiplier = 4.5,
            priority = 12,
            min_dice = 6,
            description = "All values 1-6 present (6+ dice)",
        }),
        Hand:new({
            name = "Pyramid",
            base_score = 200,
            multiplier = 10,
            priority = 13,
            min_dice = 9,
            description = "1x two, 3x fours, 5x sixes (9 dice)",
        }),
    }
end

return createHands
