local Sticker = require("objects/sticker")

local function createStickers()
	return {
		Sticker:new({
			id = "all_in",
			name = "All In",
			description = "Allows only one other sticker type on this die, but that type can stack infinitely.",
			stack_limit = 1,
			stackable = false,
			rarity = "legendary",
			svg_path = "content/stickers/all_in.svg",
			effect_hooks = { "onAttach", "onValidateAdd" },
		}),
		Sticker:new({
			id = "bad_luck",
			name = "Bad Luck?",
			description = "x1.5 base mult per stack. From round 44 onward this die can end your run each round.",
			stack_limit = 45,
			stackable = true,
			rarity = "curse",
			svg_path = "content/stickers/bad_luck.svg",
			effect_hooks = { "onRoundStart", "onPreScore" },
		}),
		Sticker:new({
			id = "lucky_streak",
			name = "Lucky Streak",
			description = "If this die repeats a value in the same round, gain +2 rerolls and boost strike chance by 33%.",
			stack_limit = 7,
			stackable = true,
			rarity = "epic",
			svg_path = "content/stickers/lucky_streak.svg",
			effect_hooks = { "onPostRoll", "onRoundStart" },
		}),
		Sticker:new({
			id = "momentum",
			name = "Momentum",
			description = "Each roll of 1 on this die scales its multiplier contribution.",
			stack_limit = 11,
			stackable = true,
			rarity = "rare",
			svg_path = "content/stickers/momentum.svg",
			effect_hooks = { "onPostRoll", "onPreScore", "onRoundStart" },
		}),
		Sticker:new({
			id = "risk_reward",
			name = "Risk / Reward",
			description = "Rolls 1-3 gain +2. Rolls 4-6 lose 1.",
			stack_limit = 1,
			stackable = false,
			rarity = "uncommon",
			svg_path = "content/stickers/risk_reward.svg",
			effect_hooks = { "onPostRoll" },
		}),
		Sticker:new({
			id = "jackpot",
			name = "Jackpot",
			description = "Rolling a 6 on this die triggers its effect extra times.",
			stack_limit = 99,
			stackable = true,
			rarity = "legendary",
			svg_path = "content/stickers/jackpot.svg",
			effect_hooks = { "onPostRoll", "onPreScore" },
		}),
		Sticker:new({
			id = "reverse",
			name = "Reverse",
			description = "Reverses values on this die (1<->6, 2<->5, 3<->4).",
			stack_limit = 1,
			stackable = false,
			rarity = "rare",
			svg_path = "content/stickers/reverse.svg",
			effect_hooks = { "onPostRoll" },
		}),
		Sticker:new({
			id = "odd_todd",
			name = "Odd Todd",
			description = "This die adds +0.5 mult when it rolls odd.",
			stack_limit = 20,
			stackable = true,
			rarity = "uncommon",
			svg_path = "content/stickers/odd_todd.svg",
			effect_hooks = { "onPreScore" },
		}),
		Sticker:new({
			id = "even_steven",
			name = "Even Steven",
			description = "This die adds +0.5 mult when it rolls even.",
			stack_limit = 20,
			stackable = true,
			rarity = "uncommon",
			svg_path = "content/stickers/even_steven.svg",
			effect_hooks = { "onPreScore" },
		}),
		Sticker:new({
			id = "loaded_dice",
			name = "Loaded Dice",
			description = "This die slightly favors high rolls.",
			stack_limit = 1,
			stackable = false,
			rarity = "rare",
			svg_path = "content/stickers/loaded_dice.svg",
			effect_hooks = { "onRoundStart" },
		}),
	}
end

return createStickers
